// 2D layout of a plan: where the plots and climate pens go around each Heat Furnace, Cooling Unit and Sunlamp.
//
// Pure functions, no DOM, like planner.js: the page draws what deviceLayouts() returns, tests run it under Node.
// Only the device areas are drawn to scale: they are the one place where position changes the numbers (a crop,
// or a pen with a climate recipe, works at its temperature only inside a device's 9x9 area). The rest of the
// home has no positions here yet; FOOTPRINT is where the other sizes go, for a full home map.
//
// What is drawn is ONE valid arrangement (the best packing, plots nearest the device), not the player's own:
// any arrangement with the same plots under the device gives the same plan.
(function (root) {
  // Size in squares (aniimo.gg Size / wikily.gg Footprint, same at every level; planner.js COVER for the first
  // five); the device area is 9 x 9 at every level
  const FOOTPRINT = { Farmland: 2, Woodland: 4, "Heat Furnace": 1, Sunlamp: 1, "Cooling Unit": 2,
    "Starfall Hammock": 5, "Tidewhisper Sandcastle": 5 };
  const AREA = 9;
  const PLOTS = ["Woodland", "Farmland"];
  // Pens with a climate recipe (Starfall Hammock: Star wants Cool -1; Tidewhisper Sandcastle: Pearl wants Warm +1), 5x5.
  // Exact packing (tools/pack-patterns.js): a 5x5 pen around a device takes exactly the room of one Woodland.
  const PENS = ["Starfall Hammock", "Tidewhisper Sandcastle"];
  const MAX_PENS = 2;                              // per device in PATTERNS (the game allows 2 Hammocks at most)

  // Best arrangement per device size, pen count p (0..2) and Woodland count k (p + k <= 8): top-left squares of
  // each pen (P), Woodland (W) and Farmland (F), the device on [0, s) x [0, s). Nearest the device first, so a
  // plan with fewer plots takes the first ones. Generated by tools/pack-patterns.js (exact 0/1 program); do not
  // edit by hand.
  const PATTERNS = {
    // PATTERNS:BEGIN (generated)
    1: [
      [   // 0 pens
        { P: [], W: [],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[-4,-1],[3,0],[-1,3],[2,-4],[-4,-3],[3,2],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4],[-4,-5],[4,-4],[-5,3],[3,4]] },   // 0 Woodland
        { P: [], W: [[3,-7]],
          F: [[-1,-2],[1,-1],[-2,0],[0,1],[1,-3],[-3,-2],[2,1],[-2,2],[-1,-4],[3,-1],[-4,0],[0,3],[-3,-4],[3,-3],[-4,2],[2,3],[1,-5],[-5,-2],[4,1],[-2,4],[-5,-4],[4,3],[-4,4]] },   // 1 Woodland
        { P: [], W: [[3,-7],[-6,4]],
          F: [[-1,-2],[1,-1],[-2,0],[0,1],[1,-3],[-3,-2],[2,1],[-2,2],[-1,-4],[3,-1],[-4,0],[0,3],[-3,-4],[3,-3],[-4,2],[2,3],[1,-5],[-5,-2],[4,1],[-2,4],[-5,-4],[4,3]] },   // 2 Woodland
        { P: [], W: [[3,-7],[-7,-6],[-6,4]],
          F: [[-1,-2],[1,-1],[-2,0],[0,1],[1,-3],[-3,-2],[2,1],[-2,2],[-1,-4],[3,-1],[-4,0],[0,3],[-3,-4],[3,-3],[-4,2],[2,3],[1,-5],[-5,-2],[4,1],[-2,4],[4,3]] },   // 3 Woodland
        { P: [], W: [[3,-7],[-7,-6],[4,3],[-6,4]],
          F: [[-1,-2],[1,-1],[-2,0],[0,1],[1,-3],[-3,-2],[2,1],[-2,2],[-1,-4],[3,-1],[-4,0],[0,3],[-3,-4],[3,-3],[-4,2],[2,3],[1,-5],[-5,-2],[4,1],[-2,4]] },   // 4 Woodland
        { P: [], W: [[3,-3],[3,-7],[-7,-6],[4,3],[-6,4]],
          F: [[-1,-2],[1,-1],[-2,0],[0,1],[1,-3],[-3,-2],[2,1],[-2,2],[-1,-4],[-4,0],[0,3],[-3,-4],[-4,2],[2,3],[1,-5],[-5,-2],[4,1],[-2,4]] },   // 5 Woodland
        { P: [], W: [[3,-3],[0,3],[3,-7],[-7,-6],[4,3],[-6,4]],
          F: [[-1,-2],[1,-1],[-2,0],[0,1],[1,-3],[-3,-2],[2,1],[-2,2],[-1,-4],[-4,0],[-3,-4],[-4,2],[1,-5],[-5,-2],[4,1],[-2,4]] },   // 6 Woodland
        { P: [], W: [[3,-3],[-6,0],[0,3],[3,-7],[-7,-6],[4,3],[-6,4]],
          F: [[-1,-2],[1,-1],[-2,0],[0,1],[1,-3],[-3,-2],[2,1],[-2,2],[-1,-4],[-3,-4],[1,-5],[-5,-2],[4,1],[-2,4]] },   // 7 Woodland
        { P: [], W: [[-3,-6],[3,-3],[-6,0],[0,3],[3,-7],[-7,-6],[4,3],[-6,4]],
          F: [[-1,-2],[1,-1],[-2,0],[0,1],[1,-3],[-3,-2],[2,1],[-2,2],[1,-5],[-5,-2],[4,1],[-2,4]] },   // 8 Woodland
      ],
      [   // 1 pens
        { P: [[4,-7]], W: [],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[-4,-1],[3,0],[-1,3],[2,-4],[-4,-3],[3,2],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4],[-4,-5],[-5,3],[3,4]] },   // 0 Woodland
        { P: [[-7,-8]], W: [[-7,3]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[-4,-1],[3,0],[-1,3],[2,-4],[-4,-3],[3,2],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4],[4,-4],[3,4]] },   // 1 Woodland
        { P: [[-7,-8]], W: [[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[-4,-1],[3,0],[-1,3],[2,-4],[-4,-3],[3,2],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4],[4,-4]] },   // 2 Woodland
        { P: [[4,-7]], W: [[-6,-7],[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[-4,-1],[3,0],[-1,3],[2,-4],[-4,-3],[3,2],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4]] },   // 3 Woodland
        { P: [[4,-7]], W: [[-6,-3],[-6,-7],[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[3,0],[-1,3],[2,-4],[3,2],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4]] },   // 4 Woodland
        { P: [[4,-7]], W: [[-6,-3],[3,0],[-6,-7],[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[-1,3],[2,-4],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4]] },   // 5 Woodland
        { P: [[4,-7]], W: [[0,-6],[-6,-3],[3,0],[-6,-7],[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[-1,3],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4]] },   // 6 Woodland
        { P: [[4,-7]], W: [[0,-6],[-6,-3],[3,0],[-3,3],[-6,-7],[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[-2,-5],[4,-2],[-5,1],[1,4]] },   // 7 Woodland
      ],
      [   // 2 pens
        { P: [[-7,-8],[4,-7]], W: [],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[-4,-1],[3,0],[-1,3],[2,-4],[-4,-3],[3,2],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4],[-5,3],[3,4]] },   // 0 Woodland
        { P: [[-7,-8],[3,4]], W: [[-7,3]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[-4,-1],[3,0],[-1,3],[2,-4],[-4,-3],[3,2],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4],[4,-4]] },   // 1 Woodland
        { P: [[-7,-8],[4,-7]], W: [[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[-4,-1],[3,0],[-1,3],[2,-4],[-4,-3],[3,2],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4]] },   // 2 Woodland
        { P: [[-7,-8],[4,-7]], W: [[-6,-3],[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[3,0],[-1,3],[2,-4],[3,2],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4]] },   // 3 Woodland
        { P: [[-7,-8],[4,-7]], W: [[-6,-3],[3,0],[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[0,-4],[-1,3],[2,-4],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4]] },   // 4 Woodland
        { P: [[-7,-8],[4,-7]], W: [[0,-6],[-6,-3],[3,0],[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[-1,3],[-3,3],[-2,-5],[4,-2],[-5,1],[1,4]] },   // 5 Woodland
        { P: [[-7,-8],[4,-7]], W: [[0,-6],[-6,-3],[3,0],[-3,3],[-7,3],[3,4]],
          F: [[0,-2],[-2,-1],[1,0],[-1,1],[-2,-3],[2,-2],[-3,1],[1,2],[-2,-5],[4,-2],[-5,1],[1,4]] },   // 6 Woodland
      ],
    ],
    2: [
      [   // 0 pens
        { P: [], W: [],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4],[-4,-4],[4,-4],[-4,4],[4,4]] },   // 0 Woodland
        { P: [], W: [[-6,-6]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4],[4,-4],[-4,4],[4,4]] },   // 1 Woodland
        { P: [], W: [[-6,-6],[4,-6]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4],[-4,4],[4,4]] },   // 2 Woodland
        { P: [], W: [[-6,-6],[4,-6],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4],[-4,4]] },   // 3 Woodland
        { P: [], W: [[-6,-6],[4,-6],[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4]] },   // 4 Woodland
        { P: [], W: [[4,-2],[-6,-6],[4,-6],[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[-4,2],[4,2],[-2,4],[2,4]] },   // 5 Woodland
        { P: [], W: [[0,-6],[4,-2],[-6,-6],[4,-6],[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[-4,0],[0,4],[-2,-4],[-4,-2],[-4,2],[4,2],[-2,4],[2,4]] },   // 6 Woodland
        { P: [], W: [[0,-6],[4,-2],[-6,0],[-6,-6],[4,-6],[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,4],[-2,-4],[-4,-2],[4,2],[-2,4],[2,4]] },   // 7 Woodland
        { P: [], W: [[0,-6],[4,-2],[-6,0],[0,4],[-6,-6],[4,-6],[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[-2,-4],[-4,-2],[4,2],[-2,4]] },   // 8 Woodland
      ],
      [   // 1 pens
        { P: [[-7,-7]], W: [],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4],[4,-4],[-4,4],[4,4]] },   // 0 Woodland
        { P: [[4,-7]], W: [[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4],[-4,-4],[-4,4]] },   // 1 Woodland
        { P: [[4,-7]], W: [[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4],[-4,-4]] },   // 2 Woodland
        { P: [[4,-7]], W: [[-6,-6],[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4]] },   // 3 Woodland
        { P: [[4,-7]], W: [[-2,-6],[-6,-6],[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[-4,0],[4,0],[0,4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4]] },   // 4 Woodland
        { P: [[4,-7]], W: [[-2,-6],[4,-2],[-6,-6],[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[-4,0],[0,4],[2,-4],[-4,-2],[-4,2],[4,2],[-2,4],[2,4]] },   // 5 Woodland
        { P: [[4,-7]], W: [[-2,-6],[4,-2],[-6,0],[-6,-6],[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,4],[2,-4],[-4,-2],[4,2],[-2,4],[2,4]] },   // 6 Woodland
        { P: [[4,-7]], W: [[-2,-6],[4,-2],[-6,0],[-2,4],[-6,-6],[-6,4],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[2,-4],[-4,-2],[4,2],[2,4]] },   // 7 Woodland
      ],
      [   // 2 pens
        { P: [[-7,-7],[4,4]], W: [],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4],[4,-4],[-4,4]] },   // 0 Woodland
        { P: [[4,-7],[-7,4]], W: [[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4],[-4,-4]] },   // 1 Woodland
        { P: [[4,-7],[-7,4]], W: [[-6,-6],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,-4],[-4,0],[4,0],[0,4],[-2,-4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4]] },   // 2 Woodland
        { P: [[4,-7],[-7,4]], W: [[-2,-6],[-6,-6],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[-4,0],[4,0],[0,4],[2,-4],[-4,-2],[4,-2],[-4,2],[4,2],[-2,4],[2,4]] },   // 3 Woodland
        { P: [[4,-7],[-7,4]], W: [[-2,-6],[4,-2],[-6,-6],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[-4,0],[0,4],[2,-4],[-4,-2],[-4,2],[4,2],[-2,4],[2,4]] },   // 4 Woodland
        { P: [[4,-7],[-7,4]], W: [[-2,-6],[4,-2],[-6,0],[-6,-6],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[0,4],[2,-4],[-4,-2],[4,2],[-2,4],[2,4]] },   // 5 Woodland
        { P: [[4,-7],[-7,4]], W: [[-2,-6],[4,-2],[-6,0],[-2,4],[-6,-6],[4,4]],
          F: [[0,-2],[-2,0],[2,0],[0,2],[-2,-2],[2,-2],[-2,2],[2,2],[2,-4],[-4,-2],[4,2],[2,4]] },   // 6 Woodland
      ],
    ],    // PATTERNS:END

  };

  const sizeOf = (device) => FOOTPRINT[device] || 1;
  const patternOf = (device, p, k) => ((PATTERNS[sizeOf(device)] || [])[p] || [])[k] || null;
  // most Farmland that fits around one device with p pens and k Woodland (planner.js PACK with a pen as one
  // Woodland: p + k <= 8, p + k + f <= 24, 2(p + k) + f <= 28); -1 when they do not fit at all
  const maxFarmland = (device, k, p) => { const q = patternOf(device, p || 0, k); return q ? q.F.length : -1; };

  // The 9x9 area in squares, for drawing: centred on the device. On a 2x2 device it is centred between squares
  // (-3.5 .. 5.5); a plot there counts by the whole squares inside, -3 .. 4 (tools/pack-patterns.js).
  function areaOf(device) {
    const s = sizeOf(device), lo = (s - AREA) / 2;
    return { x: lo, y: lo, size: AREA };
  }

  // Pens, Woodland and Farmland split over n devices of one setting. The most Farmland that fits is concave in
  // the Woodland-equivalents (pens + Woodland) with its corner on a whole number, so spreading those as evenly
  // as possible holds exactly what planner.js coverFits() allows for n devices together (a pen as one Woodland).
  function split(device, n, woodland, farmland, pens) {
    pens = pens || 0;
    const out = [];
    for (let i = 0; i < n; i++) out.push({ p: Math.floor(pens / n) + (i < pens % n ? 1 : 0), w: 0, f: 0 });
    let overflowPens = 0;
    for (const d of out) if (d.p > MAX_PENS) { overflowPens += d.p - MAX_PENS; d.p = MAX_PENS; }
    let overflowWoodland = 0;
    for (let k = 0; k < woodland; k++) {           // each Woodland to the device with the fewest equivalents
      let best = null;
      for (const d of out) if (d.p + d.w < 8 && (!best || d.p + d.w < best.p + best.w)) best = d;
      if (best) best.w++; else overflowWoodland++;
    }
    let left = farmland;
    for (const d of out) {
      d.f = Math.min(Math.max(0, maxFarmland(device, d.w, d.p)), left);
      left -= d.f;
    }
    return { devices: out, overflowFarmland: left, overflowWoodland, overflowPens };
  }

  // plan lines -> plots per crop under one device setting (null: no device), whole numbers (HiGHS gives whole
  // plots; the hand-written fallback can give a fraction, which is rounded and flagged)
  function plotsOf(lines, zoneName) {
    const out = [];
    let approx = false;
    for (const l of lines || []) {
      if (l.kind !== "crop" || !PLOTS.includes(l.facility) || (l.zone || null) !== zoneName) continue;
      const n = Math.round(l.count);
      if (Math.abs(n - l.count) > 0.01) approx = true;
      if (n > 0) out.push({ facility: l.facility, recipeId: l.recipeId, count: n });
    }
    return { plots: out, approx };
  }

  // Climate pens in the plan (the data's `temp` on the recipe the pen is set to): drawn inside the area of a
  // device with exactly that temperature, where they work at full speed. Drawing only: the plan's numbers do not
  // change (user, 2026-10-09: "only the layout, no change to coin/h or production").
  const SETTING_TEMP = { "Warm +1": 1, "Scorching +2": 2, "Cool -1": -1, "Cold -2": -2 };
  function pensOf(plan, D) {
    const out = [];
    for (const l of (plan && plan.lines) || []) {
      if (!PENS.includes(l.facility)) continue;
      const r = D && D.recipes.find((x) => x.id === l.recipeId);
      if (!r || r.temp == null) continue;
      const n = Math.round(l.benches != null ? l.benches : l.count);
      for (let i = 0; i < n; i++) out.push({ facility: l.facility, recipeId: l.recipeId, temp: r.temp });
    }
    return out;
  }

  // One drawing per device placed: { facility, setting, size, area, plots: [{ facility, recipeId, x, y, size }] }.
  // Plots that do not fit the drawing (a reach the player typed above the best packing) are listed in
  // `overflow` instead of being drawn somewhere they would not count. A pen goes in only where the plan's plots
  // leave room for it; one that does not fit is listed in `pensLeft`.
  function deviceLayouts(plan, D) {
    const out = [];
    const pens = pensOf(plan, D);
    for (const d of (plan && plan.devices) || []) {
      const zone = d.facility + " (" + d.setting + ")";
      const { plots, approx } = plotsOf(plan.lines, zone);
      const total = (fac) => plots.filter((p) => p.facility === fac).reduce((a, p) => a + p.count, 0);
      const n = Math.max(1, d.place || 1);
      const mine = [];                             // pens that want this setting's temperature, not drawn yet
      for (let i = pens.length - 1; i >= 0; i--) if (SETTING_TEMP[d.setting] === pens[i].temp) mine.unshift(pens.splice(i, 1)[0]);
      // as many of them as fit beside the plots: the plan's plots come first
      let p = mine.length, sp;
      for (; p >= 0; p--) {
        sp = split(d.facility, n, total("Woodland"), total("Farmland"), p);
        if (p === 0 || (!sp.overflowFarmland && !sp.overflowWoodland && !sp.overflowPens)) break;
      }
      // hand out the pens, then the plots crop by crop, Woodland then Farmland, device by device
      const queue = { pen: mine.slice(0, p), Woodland: [], Farmland: [] };
      for (const q of plots) for (let i = 0; i < q.count; i++) queue[q.facility].push(q);
      const s = sizeOf(d.facility);
      const put = (kind, at) => { const q = queue[kind].shift(); return { facility: q.facility, recipeId: q.recipeId, x: at[0], y: at[1], size: FOOTPRINT[q.facility] }; };
      sp.devices.forEach((q, i) => {
        const pat = patternOf(d.facility, q.p, q.w);
        const placed = [];
        if (pat) {
          for (let k = 0; k < q.p; k++) placed.push(put("pen", pat.P[k]));
          for (let k = 0; k < q.w; k++) placed.push(put("Woodland", pat.W[k]));
          for (let k = 0; k < q.f; k++) placed.push(put("Farmland", pat.F[k]));
        }
        out.push({ facility: d.facility, setting: d.setting, index: i + 1, of: n, size: s, area: areaOf(d.facility), plots: placed, approx, overflow: [], pensLeft: [] });
      });
      const count = (list) => {
        const m = new Map();
        for (const q of list) {
          const k = q.facility + "|" + q.recipeId;
          if (!m.has(k)) m.set(k, { facility: q.facility, recipeId: q.recipeId, count: 0 });
          m.get(k).count++;
        }
        return [...m.values()];
      };
      // whatever is left did not fit: listed on the last drawing of this setting
      if (out.length) {
        out[out.length - 1].overflow = count([].concat(queue.Woodland, queue.Farmland));
        out[out.length - 1].pensLeft = count(mine.slice(p));
      }
    }
    return out;
  }

  // plots with no device over them, per crop (drawn as a plain list of plots)
  function openPlots(plan) {
    return plotsOf(plan && plan.lines, null);
  }

  const api = { FOOTPRINT, AREA, PENS, PATTERNS, sizeOf, maxFarmland, areaOf, split, deviceLayouts, openPlots };
  if (typeof module !== "undefined") module.exports = api; else root.Layout = api;
})(this);
